### ISSUE TITLE
type == SSDV_TYPE_INVALID issue

### ISSUE THREAD

**Issue by Jeffrey9821** [fsphil/ssdv#3]
Hi,
Why is there two (type == SSDV_TYPE_INVALID) in ssdv_dec_is_packet(uint8_t *packet, int *errors)?

https://github.com/fsphil/ssdv/blob/3122b35260b975e982f3b085887e04409a247e43/ssdv.c#L1455

https://github.com/fsphil/ssdv/blob/3122b35260b975e982f3b085887e04409a247e43/ssdv.c#L1479

Is the (type == SSDV_TYPE_INVALID) in Line 1455 correct?

**Comment by fsphil** [comment]
Correct, but not very clearly coded. The first one attempts to performs error correction on the packet, the second one signals if all the tests (including error correction) have failed.
