### ISSUE TITLE
JPEG Cropping Pre/Post Encoding

### ISSUE THREAD

**Issue by kierzenka** [fsphil/ssdv#5]
Hello,
I am utilizing this ssdv library for a project with an Arduino Arducam 5mp mini. I am using a wide fisheye lens which captures part of the lens housing as a result - for my application, I would like to make the packet transmission as efficient as possible and think I could optimize by cropping the image down or otherwise eliminating packets which mostly contain these regions.

Is there any way at any point in the encoding process to identify which region of the image a given packet "represents" (even if not exact)? The image is already in JPEG format and there is not enough memory on the Arduino for a JPEG->Raw->JPEG processing where I crop the image in the intermediate.

Thank you

**Comment by fsphil** [comment]
The easiest way would be to have the encoder configured for the cropped image, and skip the MCU blocks from the source JPEG that are outside the crop area. The DC values would need fixing after each row but that shouldn't be too difficult.
