### ISSUE TITLE
Issues with custom implementation

### ISSUE THREAD

**Issue by jgromes** [fsphil/ssdv#6]
Hi, first of all, let me say that this is really cool project, I love the idea of sending digital images through RTTY.

That being said, while attempting to add support for SSDV in [RadioLib](https://github.com/jgromes/RadioLib), I ran into some issues. I compiled SSDV on a Ubuntu VM, and started playing around with encoding different files. To verify my implementation of the encoding chain in RadioLib, I encoded the same file (a very small jpeg, only 32x32 pixels) using the compiled ssdv from this repository in both FEC and no-FEC mode, and to my surprise, both generated only two packets. I would expect the image with FEC to be longer than that, since every packet contains 32 bytes of FEC. Is this the correct behavior?

The no-FEC data generated by my implementation were the same as what the ssdv binary outputs, so I tried to transmit that and decode in fldigi to verify at least that. However, even though fldigi decodes the RTTY and prints it to the terminal, the SSDV RX window does nothing, never even printing the callsign. I can see what should be the callsign bytes in the terminal (at leat the prinatble bits), so I think fldigi is decoding correctly, but I don't know if I'm just using it wrong. Is there a way a debug the transfer in fldigi?

I'm not sure if this repo is still maintained, just thought I'd ask. Thanks!

**Comment by fsphil** [comment]
> I would expect the image with FEC to be longer than that, since every packet contains 32 bytes of FEC. Is this the correct behavior?

Yeah that can happen. The packets are fixed size so there's usually some padding in the final packet, and in your example there's enough padding to absorb the 64 byte overhead of the FEC for both packets.

> However, even though fldigi decodes the RTTY and prints it to the terminal, the SSDV RX window does nothing, never even printing the callsign.

The non-FEC mode was added for radio modes that already provide some form of error correction or re-transmission function, so it never got added to dl-fldigi.

**Comment by jgromes** [comment]
@fsphil thanks for the reply! Guess I'll have to investigate why my implemetation is producing more data than the reference one in case when FEC is enabled (probably just an incorrect memcpy somewhere...). What confused me is that not even the callsign was shown in fldigi.

Couple more questions:

1. If the image length is not divisible by packet length, what should be used as padding? Random bytes or something else?
2. Is there a testing image that is know to be working? I'm asking because there are some conditions on what sort of JPEGs can be sent.
3. I noticed there's quite a bit of processing goign on during encoding - is it described somewhere? From reading the guide (https://ukhas.org.uk/guides:ssdv) I was under the impression that it was enough to just copy the bytes between start-of-scan and end-of-image flags of the JPEG file, but apparently that's not the case ...?

**Comment by fsphil** [comment]
>     1. If the image length is not divisible by packet length, what should be used as padding? Random bytes or something else?

It's not critical, but I fill it with random bits (`ssdv_memset_prng()`) to prevent any long runs of 0x00.

>     2. Is there a testing image that is know to be working? I'm asking because there are some conditions on what sort of JPEGs can be sent.

Not really. I haven't found many that don't work, as long as it's not too big, the width and height are multiples of 16 and it's not progressive scan. Try encoding and decoding it on the command line, compare the input and output.

>     3. I noticed there's quite a bit of processing goign on during encoding - is it described somewhere? From reading the guide (https://ukhas.org.uk/guides:ssdv) I was under the impression that it was enough to just copy the bytes between start-of-scan and end-of-image flags of the JPEG file, but apparently that's not the case ...?

The scan data is not exactly JPEG, the three important points on that page are:

* The first MCU of each packet is byte aligned
* The first DC values for each component in the first MCU of a packet are relative to 0
* The scan data does not need byte stuffing (0xFF bytes do not need to be followed by 0x00)

Also, as the DQT and DHT tables are not transmitted, the image data needs to be reencoded using the ssdv tables.

**Comment by fsphil** [comment]
> Does that mean stuffing is optional, or required to not be present?

The latter. There will never be any headers embedded in the SSDV image data so there's no need for it. Saves a little bit of space too.

If I was re-writing the encoder now I'd probably do it something like this:

0. Create an empty packet.
1. Read each 8x8 DCT block from the source JPEG, giving us 64 coefficients.
2. Requantise these using the SSDV DQT tables and write the block into the output buffer, using SSDV huffman tables and without byte stuffing.
3. Repeat from step 1 until a complete MCU is written (1-6 DCT blocks depending on the JPEG colour mode).
4. Repeat from step 1 while the output buffer is smaller than the remaining space in the packet.
5. Write the output data to the packet (from packet's MCU offset byte) until full, packet is complete - transmit.
6. Create a new empty packet, write remaining output data to the beginning of the packet.
7. Update the packet's MCU offset byte to point to the first free byte following this data.
8. If there is no free space after this, write offset 0xFF, transmit packet and repeat from step 6.
9. Reset SSDV DC offsets and go back to step 1.

**Comment by jgromes** [comment]
Thanks for the extra info - seems like the process is a little bit more involved than I was hoping for - oh well, time to refresh on JPEG encoding/decoding :)
